binocular_laser_profile_scanner:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # position controllers
  rot_table_angular_position_controller:
    type: effort_controllers/JointPositionController
    joint: rot_table_joint
    pid: {p: 10.0, i: 5.0, d: 1.0}

  scanner_angular_position_controller:
    type: effort_controllers/JointPositionController
    joint: motor_joint
    pid: {p: 10.0, i: 5.0, d: 1.0}